### ISSUE TITLE
Missing create_maindb.sql File in extra/ Folder

### ISSUE THREAD

**Issue by marsha94** [GeiserX/jwlibrary-plus#2]
Hi, I noticed that the instructions for setting up the project mention initializing the database using the `create_maindb.sql` file, which is supposed to be located in the `extra/` folder. However, this file seems to be missing from the repository.

Could you please check if this file was omitted by mistake or provide guidance on how to proceed without it? Thank you!

**Comment by GeiserX** [comment]
Hi @marsha94 I recently changed this, this is no more needed, I will update the README soon. This part is done within the code. 
This is a pretty alpha project, so everything is currently quite brittle, so expect issues. Right now the latest "stable" release is the docker image with version "0.4.61". Check it out.

**Comment by marsha94** [comment]
Thank you for the clarification, @GeiserX! I’ll try the stable release (`0.4.61`) as you suggested. Appreciate your work on this project, and I understand it’s in alpha, so I’ll keep that in mind as I test things out.
